/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AvaliacaoRouteImport } from './routes/avaliacao'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardAdminRouteImport } from './routes/dashboard-admin'
import { Route as DashboardInvestigadorRouteImport } from './routes/dashboard-investigador'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as MetricasRouteImport } from './routes/metricas'
import { Route as ModelosRouteImport } from './routes/modelos'
import { Route as MonitorizacaoRouteImport } from './routes/monitorizacao'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RegistoRouteImport } from './routes/registo'
import { Route as SimulacaoRouteImport } from './routes/simulacao'
import { Route as SistemaRouteImport } from './routes/sistema'
import { Route as TreinamentoRouteImport } from './routes/treinamento'
import { Route as UtilizadoresRouteImport } from './routes/utilizadores'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacaoRoute = AvaliacaoRouteImport.update({
  id: '/avaliacao',
  path: '/avaliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard-admin',
  path: '/dashboard-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInvestigadorRoute = DashboardInvestigadorRouteImport.update({
  id: '/dashboard-investigador',
  path: '/dashboard-investigador',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricasRoute = MetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosRoute = ModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorizacaoRoute = MonitorizacaoRouteImport.update({
  id: '/monitorizacao',
  path: '/monitorizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistoRoute = RegistoRouteImport.update({
  id: '/registo',
  path: '/registo',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacaoRoute = SimulacaoRouteImport.update({
  id: '/simulacao',
  path: '/simulacao',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemaRoute = SistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinamentoRoute = TreinamentoRouteImport.update({
  id: '/treinamento',
  path: '/treinamento',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilizadoresRoute = UtilizadoresRouteImport.update({
  id: '/utilizadores',
  path: '/utilizadores',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-admin': typeof DashboardAdminRoute
  '/dashboard-investigador': typeof DashboardInvestigadorRoute
  '/datasets': typeof DatasetsRoute
  '/historico': typeof HistoricoRoute
  '/metricas': typeof MetricasRoute
  '/modelos': typeof ModelosRoute
  '/monitorizacao': typeof MonitorizacaoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/registo': typeof RegistoRoute
  '/simulacao': typeof SimulacaoRoute
  '/sistema': typeof SistemaRoute
  '/treinamento': typeof TreinamentoRoute
  '/utilizadores': typeof UtilizadoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-admin': typeof DashboardAdminRoute
  '/dashboard-investigador': typeof DashboardInvestigadorRoute
  '/datasets': typeof DatasetsRoute
  '/historico': typeof HistoricoRoute
  '/metricas': typeof MetricasRoute
  '/modelos': typeof ModelosRoute
  '/monitorizacao': typeof MonitorizacaoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/registo': typeof RegistoRoute
  '/simulacao': typeof SimulacaoRoute
  '/sistema': typeof SistemaRoute
  '/treinamento': typeof TreinamentoRoute
  '/utilizadores': typeof UtilizadoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-admin': typeof DashboardAdminRoute
  '/dashboard-investigador': typeof DashboardInvestigadorRoute
  '/datasets': typeof DatasetsRoute
  '/historico': typeof HistoricoRoute
  '/metricas': typeof MetricasRoute
  '/modelos': typeof ModelosRoute
  '/monitorizacao': typeof MonitorizacaoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/registo': typeof RegistoRoute
  '/simulacao': typeof SimulacaoRoute
  '/sistema': typeof SistemaRoute
  '/treinamento': typeof TreinamentoRoute
  '/utilizadores': typeof UtilizadoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/avaliacao'
    | '/configuracoes'
    | '/dashboard'
    | '/dashboard-admin'
    | '/dashboard-investigador'
    | '/datasets'
    | '/historico'
    | '/metricas'
    | '/modelos'
    | '/monitorizacao'
    | '/redefinir-senha'
    | '/registo'
    | '/simulacao'
    | '/sistema'
    | '/treinamento'
    | '/utilizadores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/avaliacao'
    | '/configuracoes'
    | '/dashboard'
    | '/dashboard-admin'
    | '/dashboard-investigador'
    | '/datasets'
    | '/historico'
    | '/metricas'
    | '/modelos'
    | '/monitorizacao'
    | '/redefinir-senha'
    | '/registo'
    | '/simulacao'
    | '/sistema'
    | '/treinamento'
    | '/utilizadores'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/avaliacao'
    | '/configuracoes'
    | '/dashboard'
    | '/dashboard-admin'
    | '/dashboard-investigador'
    | '/datasets'
    | '/historico'
    | '/metricas'
    | '/modelos'
    | '/monitorizacao'
    | '/redefinir-senha'
    | '/registo'
    | '/simulacao'
    | '/sistema'
    | '/treinamento'
    | '/utilizadores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  AvaliacaoRoute: typeof AvaliacaoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardInvestigadorRoute: typeof DashboardInvestigadorRoute
  DatasetsRoute: typeof DatasetsRoute
  HistoricoRoute: typeof HistoricoRoute
  MetricasRoute: typeof MetricasRoute
  ModelosRoute: typeof ModelosRoute
  MonitorizacaoRoute: typeof MonitorizacaoRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RegistoRoute: typeof RegistoRoute
  SimulacaoRoute: typeof SimulacaoRoute
  SistemaRoute: typeof SistemaRoute
  TreinamentoRoute: typeof TreinamentoRoute
  UtilizadoresRoute: typeof UtilizadoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacao': {
      id: '/avaliacao'
      path: '/avaliacao'
      fullPath: '/avaliacao'
      preLoaderRoute: typeof AvaliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-admin': {
      id: '/dashboard-admin'
      path: '/dashboard-admin'
      fullPath: '/dashboard-admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-investigador': {
      id: '/dashboard-investigador'
      path: '/dashboard-investigador'
      fullPath: '/dashboard-investigador'
      preLoaderRoute: typeof DashboardInvestigadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metricas': {
      id: '/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof MetricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos': {
      id: '/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof ModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitorizacao': {
      id: '/monitorizacao'
      path: '/monitorizacao'
      fullPath: '/monitorizacao'
      preLoaderRoute: typeof MonitorizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registo': {
      id: '/registo'
      path: '/registo'
      fullPath: '/registo'
      preLoaderRoute: typeof RegistoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacao': {
      id: '/simulacao'
      path: '/simulacao'
      fullPath: '/simulacao'
      preLoaderRoute: typeof SimulacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema': {
      id: '/sistema'
      path: '/sistema'
      fullPath: '/sistema'
      preLoaderRoute: typeof SistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinamento': {
      id: '/treinamento'
      path: '/treinamento'
      fullPath: '/treinamento'
      preLoaderRoute: typeof TreinamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilizadores': {
      id: '/utilizadores'
      path: '/utilizadores'
      fullPath: '/utilizadores'
      preLoaderRoute: typeof UtilizadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  AvaliacaoRoute: AvaliacaoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardInvestigadorRoute: DashboardInvestigadorRoute,
  DatasetsRoute: DatasetsRoute,
  HistoricoRoute: HistoricoRoute,
  MetricasRoute: MetricasRoute,
  ModelosRoute: ModelosRoute,
  MonitorizacaoRoute: MonitorizacaoRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RegistoRoute: RegistoRoute,
  SimulacaoRoute: SimulacaoRoute,
  SistemaRoute: SistemaRoute,
  TreinamentoRoute: TreinamentoRoute,
  UtilizadoresRoute: UtilizadoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
